    html += +'<div class="row">'
      +'<div class="col-sm-12">'
        +'<div class="section">'
          +'<div class="corner tl">'
            +'<div class="a"></div>'
            +'<div class="b"></div>'
            +'<div class="c"></div>'
          +'</div>'
          +'<div class="corner tr">'
            +'<div class="a"></div>'
            +'<div class="b"></div>'
            +'<div class="c"></div>'
          +'</div>'
          +'<div class="section_content">'
      +'<div class="tweet-container2">'
      +'<div class="row green">'
        +'<div class="col-sm-10">'
          +'<div class="row.small">'
        +'<p class="name">' + author + '</p>'
      +'</div>'
          +'<div class="row.small">'
        +'<p class="handle">' + username + '</p>'
      +'</div>'
        +'</div>'
        +'<div class="col-sm-2">'
          +'<img class="tlogo" src="http://i.imgur.com/YwHzSGv.png">'
        +'</div>'
      +'</div>'
      +'<div class="row green">'
        +'<div class="col-sm-12 blue">'
        +(tweetObject.image ? '<img class="tweet-img" src="'+tweetObject.image+'" />' : '<img class="tweet-img" src="https://replayfx.org/wp-content/uploads/ReplayFX-Cosplay-2015-042.jpg">')
        +'</div>'
      +'</div>'
      +'<div class="row blue">'
        +'<div class="col-sm-12">'
          +'<div class="twext"><p class="twext">'+tweetObject.tweet+'</p></div>'
        +'</div>'
      +'</div>'
      +'</div>'
            +'<div class="corner bl">'
              +'<div class="a"></div>'
              +'<div class="c"></div>'
              +'<div class="b"></div>'
            +'</div>'
            +'<div class="corner br">'
              +'<div class="a"></div>'
              +'<div class="c"></div>'
              +'<div class="b"></div>'
            +'</div>'
            +'</div>'
      +'</div>'
      +'</div>'

  }
  html += '</div>';
  element.innerHTML = html;
}
